markdown_write
pegchose/chat-space pull request #1
Opened 2019-05-15 08:46 UTC by pegchose

2019-05-15 10:44 UTC, shingoteshima commented
こちらのPRは何のPRでしょうか？
説明を書いていただけると助かります。

2019-05-16 03:04 UTC, pegchose commented
すいません。書き忘れました。データベース設計のものです。
テキストが要求していることがよく分からなかったので、chat-spaceのuserテーブルとmessageテーブルを作りました。

2019-05-19 06:22 UTC, pegchose commented
＃WHAT
chat-spaceのデータベース設計。以前書いたものが間違っていると感じたので書きました。
＃WHY
機能させるにはテーブルが足りないと考えた。

2019-05-19 06:30 UTC, pegchose commented
＃WHAT
アソシエーションを追加
＃WHY
メッセージ、ユーザー、グループを繋げて表示するため。

2019-05-19 08:43 UTC, pegchose commented
#WHAT
中間テーブル作成およびアソシエーション作成
#WHY
自らの間違いを発見した。これによってしっかりデータベースが動くはず。

2019-05-19 08:52 UTC, ken-nag reviewed
本プルリクはデータベース設計をするものです
なので設計ができていないのに先にmigrationを作成してdbを設計するのは二度手間になってしまうので止めましょう

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +|message_id|integer|
message_idではなくidでは

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +|user_id|integer|foreign_key: true|
userのidを外部キーとしてusersテーブルが保持することはありません

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +|group_id|integer|foreign_key: true|
has_manyな関係で外部キーは持ちません

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +- has_many :groups, through: users_messages
users_messagesを経由してgroupを参照するのではなく、userとgroupの中間テーブルを作りましょう

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +|user_id|integer|
user_idの管理は中間テーブルに任せましょう

2019-05-19 08:52 UTC, nagatomokent commented on README.md
> +|messages_id|integer|foreign_key: true|
userとgroupの中間テーブルなのにmessagesを管理するのは中間テーブルの概念として良くないです

2019-05-19 09:00 UTC, pegchose commented on README.md
> +- has_many :groups, through: users_messages
はい、それに気付いたので『chat-spaceデータベース再設計』で直しました。

2019-05-19 09:16 UTC, pegchose commented
一度に一回の変更ではなく、すいません

2019-05-19 09:20 UTC, pegchose commented
先にmigrationしてしまったのは注意が足りてませんでした。確かにおっしゃる通りです。以後気をつけます。

2019-05-19 09:28 UTC, pegchose commented on README.md
> +|message_id|integer|
確かにmessgeテーブルにidは自動で作られるので、自らidを設定する必要性は無いなとご指摘をいただいて思いました。なので消去してみました。

2019-05-19 09:41 UTC, pegchose commented on README.md
> +|user_id|integer|foreign_key: true|
これも考えてみてご指摘通りだと思いました。

2019-05-19 10:26 UTC, pegchose commented
#WHAT
ご指摘いただいた箇所を訂正
＃WHY
不必要なカラム消去で軽量化

2019-05-19 10:49 UTC, ghost requested changes
マイグレーションファイルはこちらのプルリクエストが完了してから作ってください。
また、指摘された部分で修正できていない部分があるので、修正をお願い致します。

2019-05-19 10:49 UTC, hiroki5123 commented on README.md
> +|messages_id|integer|foreign_key: true|
こちら修正をお願い致します

2019-05-19 10:49 UTC, hiroki5123 commented on README.md
> +|user_id|integer|
こちら修正をお願い致します

2019-05-19 10:49 UTC, hiroki5123 commented on README.md
> +|group_id|integer|foreign_key: true|
こちら修正をお願い致します

2019-05-19 10:58 UTC, nagatomokent commented
上記コメント確認して修正不足分を修正してください

2019-05-19 11:35 UTC, ghost requested changes
マイグレーションファイルはこちらの変更差分に含まないでください、

2019-05-19 11:35 UTC, hiroki5123 commented on README.md
> +|body|text|null: false|
NOT NULL制約を外しましょう

2019-05-19 11:35 UTC, hiroki5123 commented on README.md
> +## Association
アソシエーションが１つ足りないので見直してみましょう

2019-05-19 11:35 UTC, hiroki5123 commented on README.md
> +### Asociation
アソシエーションが１つ足りないので見直してみましょう

2019-05-20 05:51 UTC, TOMARUMARU reviewed
過去に指摘されている箇所が修正されていないようなので、全て見直してください

2019-05-20 05:51 UTC, TOMARUMARU commented on README.md
> +- belongs_to :users_groups
こちらは不要です

2019-05-20 05:51 UTC, TOMARUMARU commented on README.md
> +- belongs_to :group
groupと二度組まれてるのはおかしいですね

2019-05-20 05:51 UTC, TOMARUMARU commented on README.md
> +- has_many :groups
アソシエーション間違っています

2019-05-20 06:32 UTC, kuroko918 commented on README.md
>  * ...
この行より上の不要な記述は消しましょう！

2019-05-20 06:38 UTC, kuroko918 commented on README.md
> +- has_many :groups, through: users_groups
中間テーブルとのアソシエーションが抜けていますね！

2019-05-20 06:38 UTC, kuroko918 commented on README.md
> +- has_many :messages
中間テーブルとのアソシエーションが抜けていますね！

2019-05-20 06:40 UTC, kuroko918 commented on README.md
> +- has_many :user
外部キーカラムがあるのでbelongs_toですね！

2019-05-20 06:40 UTC, kuroko918 commented on README.md
> +- has_many :group
外部キーカラムがあるのでbelongs_toですね！

2019-05-20 07:05 UTC, i-date commented on README.md
> +|body|text|null: false|
こちら`null: false`を削除しましょう。

2019-05-20 07:05 UTC, i-date commented on README.md
> +- has_many :groups, through: users_groups
users_groupsの前に`:`を付けて、`〜, through: :users_groups`としましょう。
また、`has_many :users_groups`を追加しましょう。

2019-05-20 07:05 UTC, i-date commented on README.md
> +- has_many :users, through: users_groups
こちらもusers_groupsの前に:を付けて、`〜, through: :users_groups`としましょう。
また、`has_many :users_groups`を追加しましょう。

2019-05-20 07:05 UTC, i-date commented on README.md
> +|user_id|integer|foreign_key: true|
Railsでは外部キーは integer 型ではなく、references 型を使用しましょう。
そうでない場合、`foreign_key: true`では外部キー制約にならないので注意です。
また、そうすることで `user_id` を `user` と記述するとテーブルが生成される時に _id が付与されます。
例：`|user|references|null: false, foreign_key: true|`
あと他の外部キーも修正しましょう。

2019-05-20 07:19 UTC, i-date approved these changes
お疲れ様でしたLGTMですので、マージして次に進みましょう！
また、新機能の追加や新たにマークアップを行う際（特にカリキュラムで指定されている箇所）には新しいプルリクを作成しましょう^^

ご参考までに。
レビューを依頼する際には、[WIP]は外してからレビューを依頼するといいでしょう^^
WIP = 作業中 なので、一通り作業が完了→WIP外す→レビュー依頼、という流れになります！

2019-05-20 07:22 UTC, pegchose commented
ありがとうございます。丁寧なご指摘新たなinputにつながりました。ありがとうございました。

2019-05-20 07:23 UTC, merged